# Notebook-related checks

name: Presubmit checks

on:
  # Relevant PRs
  pull_request:
    paths:
    - "google/**"
    - "tests/**"
    - "samples/**"
    - "pyproject.toml"
    - "setup.py"
  # Allow manual runs
  workflow_dispatch:

jobs:
  test3_12:
    name: Test Py3.12
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Run tests
      run: |
        python --version
        pip install .[dev]
        python -m unittest
  test3_11:
    name: Test Py3.11
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Run tests
      run: |
        python --version
        pip install .[dev]
        python -m unittest
  test3_10:
    name: Test Py3.10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run tests
      run: |
        python --version
        pip install -q .[dev]
        python -m unittest
  test3_9:
    name: Test Py3.9
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Run tests
      run: |
        python --version
        pip install .[dev]
        python -m unittest
  pytype3_11:
    name: pytype 3.11
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Run pytype
      run: |
        python --version
        pip install .[dev]
        pip install -q gspread ipython
        touch google/__init__.py   # https://github.com/google/pytype/issues/464
        pytype
  format:
    name: Check format with black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Check format
      run: |
        python --version
        pip install -q .
        pip install -q black
        black . --check

